### ISSUE TITLE
Add Max-Width to Table Columns

### ISSUE THREAD

**Issue by andyjzhong** [andyjzhong/capstone#8]

**Comment by andyjzhong** [comment]
Added 
```css
table {
  table-layout: fixed
}
```
